### ISSUE TITLE
Node dependency lockfile

### ISSUE THREAD

**Issue by matteeyah** [vinorodrigues/bootstrap-dark-5#11]
Why doesn't this project have a node dependency lockfile checked in? It'll make resolving dependencies easier.

**Comment by vinorodrigues** [comment]
I didn't want to include the lock file because it get rebuilt anyway. 

Yes I'm aware that in the future some dependancy upgrade may break the build, but this is a proof of concept - not a product - and so I'm okay will letting the community attend to dependancy breaks.

BTW :- you will notice that in the `package.json` file one can lock in the version with `~`, `^` or `*` - so if done correctly the above point is moot.

`npm install` will generate the lock file anyway.

**Comment by vinorodrigues** [comment]
Tho this [StackOverflow answer](https://stackoverflow.com/questions/44206782/#answer-44210813) would clearly disagree with me.  Umm...

**Comment by Carl-Hugo** [comment]
> I didn't want to include the lock file because it get rebuilt anyway.
> 
> Yes I'm aware that in the future some dependancy upgrade may break the build, but this is a proof of concept - not a product - and so I'm okay will letting the community attend to dependancy breaks.
> 
> BTW :- you will notice that in the `package.json` file one can lock in the version with `~`, `^` or `*` - so if done correctly the above point is moot.
> 
> `npm install` will generate the lock file anyway.

I'm no node expert, but the `.lock` file allows to resolve dependencies deterministically (a.k.a. recreate the environment as it was on that commit) and should be checked in.

**Comment by matteeyah** [comment]
If you don't have a lockfile, every time you run `npm install` it will resolve the dependencies based on the `package.json` config. This means that the exact dependency versions always get computed again. With a lockfile, every single time you `install` with the same lockfile it ends up using the same exact dependency versions. `yarn upgrade` or the `npm` equivalent upgrades the lockfile (while taking into account the dependency versions declared in `package.json`)

**Comment by vinorodrigues** [comment]
Ok ok.  I give in. 😀
