### ISSUE TITLE
add @if $enable-dark-mode == true {

### ISSUE THREAD

**Issue by danny007in** [vinorodrigues/bootstrap-dark-5#20]
Because for https://github.com/sass/dart-sass/issues/1004

```scss
// stylelint-disable no-invalid-position-at-import-rule
@if $enable-dark-mode == true {
  @include color-scheme-alt(alternative-color-scheme($default-color-scheme)) {
    @import "../bootstrap-dark";
    @import "../layout-dark";
  }

  // Additional Global Utilities
  @import "../dark/bootstrap/utilities/api-all";
}
```

is was trying

**Comment by danny007in** [comment]
add it in in-build
like
```scss
@if $enable-dark-mode == true {
  .form-floating {
  
    // > label {
    //   border: $input-border-width solid transparent; // Required for aligning label's text with the input as it affects inner box model
    // }
  
    > .form-control {
      // &::placeholder {
      //   color: transparent;
      // }
    }
  
    > .form-control:focus,
    > .form-control:not(:placeholder-shown),
    > .form-select {
      ~ label {
        opacity: $form-floating-label-opacity-alt;
      }
    }
    // Duplicated because `:-webkit-autofill` invalidates other selectors when grouped
    > .form-control:-webkit-autofill {
      ~ label {
        opacity: $form-floating-label-opacity-alt;
      }
    }
  }
}
```

**Comment by vinorodrigues** [comment]
I see what you're trying to do here:
You want to compile in the dark-mode scss only if you have a variable (`$enable-dark-mode`) in your own scss, but dart-sass does not allow `@include` 's inside `@if` 's.

I don't have an answer for you here 😢 - your suggestion to add the `@if` clause in this code base does not seem the correct approach either: means editing >50 files, and adding another variable.

Remember this code is a proof of concept - the concept is that Bootstrap can have dark-mode.  I'm not developing a framework to be used commercially (although I do realise that it will be used as such, and I try to make that possible, e.g. hosting on NPMjs etc. - but I've never made the promise that I would address production issues.)

Also, this issue is based on known SASS issue (see [$451](https://github.com/sass/sass/issues/451)) and if you read the commentary on that they will not fix that.  There are some suggestions in there that point to using mixins etc. to make it work - maybe that's something you can explore.

But as to this issue - I'm going to mark as "won't fix".   (...sorry...)
