### ISSUE TITLE
Create a CI/CD Pipeline and deploy to NPM

### ISSUE THREAD

**Issue by Carl-Hugo** [vinorodrigues/bootstrap-dark-5#3]
If you are interested, I'd like to contribute a  CI/CD pipeline.
I suggest creating a GitHub Action that would:

1. Build the assets (enforcing that the code "compile").
2. Set a version number automatically. I suggest basing the version numbers on git history using [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) instead of tags, but tags could be fine too, or both. This should remove the versioning management off contributors' hands (aka off your hands).
3. Deploy the assets to your CDN (no more need to manually do it).
4. Deploy the assets to NPM, to install it like `npm i bootstrap-dark-5`.
5. Deploy the assets as a GitHub release (if that's something you want).

We could also (now or later) add a linter to enforce style rules within the codebase and whatever else we could want to check/enforce.

What do you think?

**Comment by vinorodrigues** [comment]
Love it!!

Just a few thoughts to consider ...
2.   YES!!!  I've been thinking of adding a "bump" function to the NPM Scripts - just not got round to it yet.  In the past I used to use Gulp and had the bumping all sorted ... with NPMS ... well I just have not looked at it yet.  If there is a better way, then I'm all ears.
3. I'm using [JSDelivr](https://www.jsdelivr.com/) right now... deployment is already automated.  It works by directly scraping from GitHub based on "release" ... also depends on specific a SemVer format on the "release"'s on GitHub *(that's why I've been using 0.0.x instead of 1.x.x-alpha)*.  I'm very happy with JSDelivr right now, so changing that will need some convincing.
4. Ummm... I've sort of prepared the `package.json` for this ... sort of ... at least added the "files" bit.  From my other projects I then just do a `NPM LOGIN` and then a `NPM PUBLISH.  But that's all manual.  Excited to see an automated way of doing this.  (The other thing is that I don't want it on NPM until I think that the code is bug free... not confident yet.)
5. Yes!  Already doing manual ... (see point 3) ... love to see it based on a specific trigger, including version bump etc.

One last thing ... can I ask that you create new branch on this effort so that I can isolate your efforts from mine.

PS: Thank you!!

**Comment by vinorodrigues** [comment]
PS... Linting is already there.   NPMS for `build`, `watch`, and `css` use StyleLint.  Also, for me, I use VSCode - and that does Linting on the fly (as I type) ... plugin required, but I also included the `.vscode` folder with a *"recommends"* plugin bit.

**Comment by Carl-Hugo** [comment]
Great, I'll look into that. 

> I'm using JSDelivr right now...

JSDelivr is fine by me.

> I don't want it on NPM until I think that the code is bug free.

"bug-free" is a rare thing 😉 
Seriously, what's the difference between deploying to GitHub Release, JSDeliver, git `dist` directory, and NPM?

I'd suggest that we deploy to NPM for two reasons:

1. It's just another way to distribute the code
2. It will allow us to "take ownership" of the package name

> can I ask that you create new branch on this effort so that I can isolate your efforts from mine.

Always.

> Linting is already there

I'll have a look at what is there. The goal would be to make a "build" fail if the rules are not as respected during a PR.
This could become a future improvement tho, so we don't enforce rules that are too crazy for no reason (aka, listing/discussing what we'd like to enforce first).

**Comment by vinorodrigues** [comment]
> "bug-free" is a rare thing

Darn.  You're so right!  I've procrastinated long enough.  

Okay ... seems `npmjs.com/bootstrap-dark` is already taken :(

I've created `npmjs.com/bootstrap-dark-4` (for the original work) and `npmjs.com/bootstrap-dark-5` (for this spin off).  Next, ... please show us how.

I'm going to close this as an "issue" ... speak to you on Slack.. OK.

Please do branch a CI/CD pipeline if & when you have time --- I would love to know how to do that.  :)

**Comment by Carl-Hugo** [comment]
I suggest we keep the issue open and close it only when done (if you disagree, please close it again).
You should not see GitHub Issues as problems; they are also conversation and work-items.

On GitHub:
- We can assign issues to people to work on it. 
- We can also tag issues, like "backlog", "in-progress", whatever. 
- We can also create project boards where we keep track of the work and even auto-close completed issues.

![image](https://user-images.githubusercontent.com/5885505/105723381-b795a180-5ef4-11eb-8d1a-97c397d56653.png)

Side note: I want to look into it this week.

**Comment by pamgaiguer** [comment]
Talking about a NPM package, im trying to install it on an Angular project, but some functions we might gonna need to rewrite to work in the scope. What do you guys reckon about this idea?

**Comment by vinorodrigues** [comment]
The POC is geared at emulating Bootstrap 5 core project insofar as providing additional SCSS to allow users to build dark-mode enabled CSS.  No attempt is made at developing (or even testing for) for any other framework - including Angular.

**Comment by pamgaiguer** [comment]
![image](https://user-images.githubusercontent.com/1967311/155657290-db0577b2-a305-4e2f-8f0e-0b41ee46989e.png)

**Comment by pamgaiguer** [comment]
oooo Thank you ! I'll try to make it work and i'll let you know (:

**Comment by vinorodrigues** [comment]
closing pipeline as BS 5.3 will introduce Darkmode making this entire project moot.
