### ISSUE TITLE
Last table example in dark mode text color stays black.

### ISSUE THREAD

**Issue by mechdog** [vinorodrigues/bootstrap-dark-5#40]
On the last example of the tables, the text in the table stays black instead of switching to white. Not sure if it is an issue outside of the example but I wanted to give you a heads up.

https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-nightshade.html

![Screen Shot 2021-11-08 at 1 00 53 PM](https://user-images.githubusercontent.com/478017/140794027-9a55aced-d612-48ce-bb2b-d81aefd92cf8.png)

**Comment by vinorodrigues** [comment]
Yip - sorry - my fault ... been working on the latest sources from BS5.  Commit [#35055](https://github.com/twbs/bootstrap/commit/5b124f647fd618cef8115f09da61c095e5c85ffe) fixed the `color` for table (now uses CSS vars), but that commit is **after** v5.1.3.  I'd removed the redundant `color` decls.

This suff happens when relying on an external dependancy with a moving target.

Will fix/regress now to account for the NPM v5.1.1 dependancy (as apposed to GitHub "latest").   Hope I remember to set it back on the next update of core :(
