### ISSUE TITLE
Compile error on "bootstrap-dark-plugin.scss"

### ISSUE THREAD

**Issue by JEK58** [vinorodrigues/bootstrap-dark-5#42]
Am I missing something or does "bootstrap-dark-plugin.scss" not compile correctly?

Whenever I try I get an error:

```Error: Can't find stylesheet to import.
  15 │ @import "functions";

    node_modules/bootstrap-dark-5/scss/bootstrap-dark-plugin.scss 15:9  @import
```

This is what my scss looks like:

@import "../node_modules/bootstrap/scss/bootstrap";
@import "../node_modules/bootstrap-dark-5/scss/bootstrap-dark-plugin.scss";

(I'm using it in vue with vite)

**Comment by vinorodrigues** [comment]
1st: This is a Proof Of Concept - I offer no support on this work.

2nd: Nope - I'm not getting an error.   From what you've given me you're attempting to import the whole of `bootstrap` and then the whole of `bootstrap-dark-plugin` ... `bootstrap-dark` already does this.

If you're trying to incorporate into a larger body of work then you need to be cognisant of the paths, and the fact the you may end up with `.scss` files that have the same name, therefor confusing the SASS compiler.  The SASS authors have already deprecated the use of `@import` just for this very reason. (See [here](https://sass-lang.com/documentation/at-rules/import).)

With `bootstrap-dark-5` as the root on the SASS compile it works it way around with the `--load-path` parameter.  The `package.json` has a runscript:

```
"css-compile": "sass --style expanded --source-map --embed-sources --no-error-css --load-path=node_modules/bootstrap/scss scss/:dist/css/",
```

If this does not help then try individual `@import`'s ... or copy the **content** of the `bootstrap-dark-plugin.scss` file into your own SCSS.

**Comment by vinorodrigues** [comment]
Also please read the README.md file, specifically the notes under "[Can I use this](https://github.com/vinorodrigues/bootstrap-dark-5#note-1)".

**Comment by 537mfb** [comment]
@JEK58 there are 3 imports in bootstrap-dark-plugin.scss (and others) that aren't in the package, namely:

```
@import "functions";
@import "variables";  // defaults are here
@import "mixins";
@import "utilities";
```

Removing those imports seems to work - haven't seen anything off yet

My advice if you want to use this project is to copy botstrap-dark-plugin.scss to your own asset folder, remove those 4 lines, fix the paths for the rest of the imports and import that copy in your project instead of the one in the package

But like @vinorodrigues said: this project is a proof of concept - use in production at your own risk
No guarantees it will work flawlessly at all times or if it will suit your requirements in the long term

**Comment by JEK58** [comment]
Thank you very much for your help.
