### ISSUE TITLE
bootstrap-unlit has unexpected result

### ISSUE THREAD

**Issue by rabbit59** [vinorodrigues/bootstrap-dark-5#48]
The bootstrap-unlit.css colours appear to mostly white, using the demo project for unlit at https://github.com/vinorodrigues/bootstrap-dark-5/blob/main/docs/bootstrap-unlit.md and adding samples using the text-* colour utility classes does not produce the expected result.  Note that changing the stylesheet to bootstrap-dark.css produces the correct result.  See attached sample html.
[unlit.zip](https://github.com/vinorodrigues/bootstrap-dark-5/files/7775239/unlit.zip)

**Comment by vinorodrigues** [comment]
Acknowledged - the CSS is only generated in the "secondary" portion of the CSS. So "unlit", that is default / primary, dark does not have a definition of `.text-*` (or `.bg-*` etc.

I will need to fix this. :(

**Comment by vinorodrigues** [comment]
Ok - found the problem.  In my original code I had omitted the `local-vars: ("text-opacity": 1)` bit from the `color` *(and the equal for background)* because there was no need to redefine a local var on the dark mode media query.

But with `unlit` - that swaps the schemes via the `-alt` variables around - this meant that the `text-` and `bg-` classes also got that bit missing, thus breaking those classes as the color defs would be:
```css
color: rgba(var(--bs-whatever-rgb), var(--bs-text-opacity)) !important;
```
And CSS would just ignore that since there was no `--bs-text-opacity` and thus the color would fall back to the `body` def.

Another way to make sure this does not happen is to define the CSS var's with a default, i.e.:
```css
color: rgba(var(--bs-whatever-rgb), var(--bs-text-opacity, 1)) !important;
```
but nothing in BS core is defined like that so I wont do here too.

Hence - putting the `local-vars: ("text-opacity": 1)` fixes the issue, but also adds size to all the variants.

**Comment by vinorodrigues** [comment]
@rabbit59 - thanks for letting me know

**Comment by rabbit59** [comment]
Thank you for the fix :)
