### ISSUE TITLE
How to compile sass files?

### ISSUE THREAD

**Issue by mastersuv** [vinorodrigues/bootstrap-dark-5#53]
Can I get some insight on how to compile this with sass? What do I need to @import?

Thank you

**Comment by vinorodrigues** [comment]
This project is a Proof Of Concept and offers no support.  If you have an issue with the code, then the assumption is made that you will figure it out yourself in the process of incorporating its ideas into your own code.

It is also well known that Bootstrap, as a framework, is highly opinionated, and as such will attract much debate ... this is not the forum for that and recommendations to change the way things are written in this work will be, for the most, ignored.  Opinions on this specific code, e.g. this color instead of that color, will not be tolerated – you will be blocked. You are however very welcome to fork from here (see: https://docs.github.com/en/get-started/quickstart/fork-a-repo) and change to your heart's content.

If you however find a typo or other logic error in the code then I would much appreciate you pointing out the error, and if appropriate suggested code to correct the error.

**Comment by mastersuv** [comment]
Man, I was just asking for a little help to compile the sass files...

Here's for anyone struggling with the same thing. (I'm new to sass, so I'm not sure if this is the right way to do it).

1. Download this repository and copy the following files into your own Bootstrap /scss folder:
    Folder: **/dark**
    File: **_variables-alt.scss**
    File: **bootstrap-dark.scss** (or the one of your interest)
2. Create a custom.scss file in your Bootstrap root folder and compile:
```
@import "scss/bootstrap";
@import "scss/bootstrap-dark";
```
