### ISSUE TITLE
Night minified version doesn't include text coloring classes

### ISSUE THREAD

**Issue by Lefky** [vinorodrigues/bootstrap-dark-5#80]
The cdn versions of bootstrap-night don't include the text color classes like it does in the non-minified version

For example this entry is missing: https://github.com/vinorodrigues/bootstrap-dark-5/blob/main/dist/css/bootstrap-night.css#L7709

Not present here
https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css
https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.css

Edit:
The same seems to be going for the respective background classes like this one:
https://github.com/vinorodrigues/bootstrap-dark-5/blob/main/dist/css/bootstrap-night.css#L7825

**Comment by vinorodrigues** [comment]
...and nor does the non-minified variant.  This issue was identified in issue #52 (the underlying error is the same).  Refer to [my comment](https://github.com/vinorodrigues/bootstrap-dark-5/issues/52#issuecomment-1012167609) about not using the NPM variant for now -  this is corrected in the GitHub repo.  The NPM repo will only be updated on the next 5.2 release of Bootstrap *(and 1.2 release of this work )*.

Also like to point out that this is still ... and will remain a Proof Of Concept.  *(Best for self hosting.)*

If you really must hotlink then use:
[`https://combinatronics.com/vinorodrigues/bootstrap-dark-5/main/dist/css/bootstrap-night.css`](https://combinatronics.com/vinorodrigues/bootstrap-dark-5/main/dist/css/bootstrap-night.css)
